version: "3.8"

services:
  twitch-bot:
    container_name: bot
    build: ./
    volumes:
      - ${OBS_SCREENSHOT}:/images
    ports:
      - "3000:3000"
      - "42394:42394"
    restart: unless-stopped
  # dashboard:
  #   container_name: dashboard
  #   image: node:lts-alpine
  #   ports:
  #     - "80:4000"
  #   restart: unless-stopped