version: "3.8"

services:
  twitch-bot:
    container_name: bot
    build: ./
    volumes:
      - ${OBS_SCREENSHOT}:/home/node/app/images
      - ./logs:/home/node/app/logs
      - ./data:/home/node/app/data
    env_file: .env
    ports:
      - "3000:3000"
      - "8080:8080"
    mem_limit: 2g
    restart: unless-stopped
  # dashboard:
  #   container_name: dashboard
  #   image: node:lts-alpine
  #   ports:
  #     - "80:4000"
  #   restart: unless-stopped