export enum Events {
  onChat = 'onChat',
  onRaid = 'onRaid',
  onHost = 'onHost',
  onSub = 'onSub',
  onBits = 'onBits',
  onDonate = 'onDonate',
  onShoutout = 'onShoutout',
  onChannelRedeem = 'onChannelRedeem',
  onCommand = 'onCommand',
  onSetGame = 'onSetGame',
  onOutro = 'onOutro',
  onScreenshot = 'onScreenshot',
  onClip = 'onClip',
  onPostClip = 'onPostClip',
  onCreateClip = 'onCreateClip',
  onBRB = 'onBRB',
  toSay = 'toSay',
  onStreamLive = 'onStreamLive',
  onStreamOffline = 'onStreamOffline',
  toPostLive = 'toPostLive',
  onRewardComplete = 'onRewardComplete',
  onGetGame = 'onGetGame',
  toUpdateReward = 'toUpdateReward'
}